hangman/routes.py
from flask import  render_template, request, redirect, url_for, flash, Blueprint, session
from flask_login import  login_user, logout_user, current_user,login_required
from hangman.forms import LoginForm, RegistrationForm, RequestResetForm, ResetPasswordForm, UpdateAccountForm
from hangman.models import User,Game,Unauthenticated_User
from hangman.utils import send_reset_email, send_confirmation_email,save_picture, serialise, deserialise, schedule_user_removal

from hangman.logic import Hangman

user=Blueprint('user',__name__)

from hangman import db,login_manager,bcrypt

@user.route("/")
@user.route("/about")
def about():
    if current_user.is_authenticated:
        return redirect(url_for('user.home'))
    return render_template("about.html")

@user.route('/home')
@login_required
def home():
    return render_template('home.html')

@user.route('/rules')
def rules():
    return render_template('rules.html')

@user.route("/profile",methods=["POST","GET"])
def profile():
    player_games=Game.query.filter_by(player=current_user)
    return render_template('profile.html',user=current_user,games=player_games.order_by(Game.date_played.desc()).all(),games_played=player_games.count())

@user.route("/register",methods=["POST","GET"])
def register():
    form=RegistrationForm()
    
    if form.validate_on_submit():  

        hashed_password=bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        if not User.query.filter_by(email=form.email.data).first() and not Unauthenticated_User.query.filter_by(email=form.email.data).first() :
            user=Unauthenticated_User(username=form.username.data,email= form.email.data, password=hashed_password)
            send_confirmation_email(user)
            db.session.add(user)
            db.session.commit()
            schedule_user_removal(user)
            flash("Your account has been created! You are now able to log in after email confirmation", 'success')
            return redirect(url_for('user.login'))
        elif User.query.filter_by(email=form.email.data).first():
            flash('Email already exists.', 'danger')
            return redirect(url_for('user.register'))
        elif Unauthenticated_User.query.filter_by(email=form.email.data).first():
            flash('Email already registered. Please check your email for a confirmation link.', 'danger')
            return redirect(url_for('user.login'))
        
    return render_template('register.html', form=form)

@user.route("/confirm/<token>",methods=["GET","POST"])
def confirm_email(token):
    if current_user.is_authenticated:
        return redirect(url_for("main.home"))
    email=Unauthenticated_User.verify_confirmation_token(token)
    if User.query.filter_by(email=email).first():
        flash('Account already confirmed. Please log in.', 'success')
        return redirect(url_for('user.login'))
    if not email:
        flash("Invalid or expired token", 'danger')
        return redirect(url_for('user.register'))
    user=Unauthenticated_User.query.filter_by(email=email).first()

    if user:
        new_user=User(email=user.email,username=user.username,password=user.password)
        db.session.add(new_user)
        db.session.commit()
        db.session.delete(user)
        db.session.commit()
        flash("Your account has been confirmed! You are now able to log in", 'success')
        return render_template('confirm_email.html')
    flash("Something went wrong. Please try again.","danger")
    return redirect(url_for("user.register"))


@user.route("/login",methods=["POST","GET"])
def login():
    if current_user.is_authenticated:
        return redirect(url_for('user.home'))
    form = LoginForm()
    if form.validate_on_submit():
        #user(email,id,username)
        user = User.query.filter_by(email=form.email.data).first()
        if user and bcrypt.check_password_hash(user.password, form.password.data):
            login_user(user,remember=form.remember.data)
            flash('You have been logged in!', 'success')
            next_page=request.args.get('next')
            return redirect(next_page) if next_page else redirect(url_for('user.home'))
        else:
            flash('Login Unsuccessful.Please check email and password','danger')
    return render_template('login.html', form=form)

@user.route("/logout")
def logout():
    logout_user()
    return redirect(url_for('user.about'))

@user.route("/update",methods=["POST","GET"])
@login_required
def update():
    form=UpdateAccountForm()    
    if form.validate_on_submit():
        if form.picture.data:
            picture_file = save_picture(form.picture.data)
            current_user.picture=picture_file
        current_user.username=form.username.data
        current_user.email=form.email.data
        db.session.commit()
        flash("Your account has been updated!","success")
        return redirect(url_for("user.profile"))
    elif request.method=="GET":
        form.username.data=current_user.username
        form.email.data=current_user.email
    picture=url_for('static',filename='profile_pics/'+current_user.picture)
    return render_template("account.html",title="Account",picture=picture,form=form)

@user.route("/reset_password",methods=["GET","POST"])
def reset_request():
    if current_user.is_authenticated:
        return redirect(url_for("main.home"))
    form=RequestResetForm()
    if form.validate_on_submit():
        user=User.query.filter_by(email=form.email.data).first()
        send_reset_email(user)
        flash("An email has been sent with instructions to reset your password.","info")
        return redirect(url_for("user.login"))
    return render_template("reset_request.html",title="Reset Password",form=form,legend="Reset Password")

@user.route("/reset_password/<token>",methods=["GET","POST"])
def reset_token(token):
    if current_user.is_authenticated:
        return redirect(url_for("main.home"))
    user=User.verify_reset_token(token)
    if not user:
        flash("Invalid or expired token", "warning")
        return redirect(url_for("user.reset_request"))
    form=ResetPasswordForm()
    if form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        user.password=hashed_password
        db.session.commit()
        flash(f"Your password has been updated!You are now able to login", "success")
        return redirect(url_for("user.login"))
    return render_template("reset_token.html",title="Reset Password",form=form,legend="Reset Password")

@login_required
@user.route("/play",methods=["GET","POST"])
def play():
    if request.method=="GET":
        if 'game' not in session: 
            session['game'] = serialise(Hangman()) # Initialize the game in the session 
    game = deserialise(session['game']) 
    if request.method == 'POST' and not game.game_over: 
        guess = request.form.get('guess').casefold()
        if guess in game.guessed or guess in game.guessed_letters:
            flash("You have already tried that guess. Please enter a new guess.","danger")
        elif not guess.isalpha():
            flash("Thats not a valid guess. Please enter a letter.","danger")
        else:
            game.check_guess(guess) 
            game.check_win() 
            session['game'] = serialise(game) 
            session.modified = True 
            if game.win: 
                game=Game(word=game.word,player=User.query.filter_by(username=current_user.username).first(),status="won")   
                db.session.add(game)
                db.session.commit()             
                session.pop('game',None)
                return render_template('win.html', word=game.word) 
            elif game.game_over: 
                game=Game(word=game.word,player=User.query.filter_by(username=current_user.username).first())   
                db.session.add(game)
                db.session.commit()             
                session.pop('game',None)
                return render_template('lose.html',word=game.word) 
    return render_template('play.html', 
                            word=' '.join(game.guessed), 
                            incorrect_guesses=' '.join(game.guessed_letters),
                            hangman_drawing=game.draw_hangman())
    

hangman/templates/about.html
{% extends "layout.html" %}

{% block content %}
<audio id="bgm" autoplay loop> 
    <source src="{{ url_for('static', filename='audio/bgm.mp3') }}" type="audio/mpeg"> 
    Your browser does not support the audio element. 
</audio>
<h1>Hangman Game Rules</h1> 
<h2>Overview</h2> 
<p>Hangman is a classic word guessing game where players try to guess a hidden word by suggesting letters within a certain number of guesses.</p> 
<h2>How to Play</h2> 
<ol> 
    <li>One player thinks of a word and writes down a series of dashes, representing each letter of the word. Alternatively, a random word generator can be used.</li> 
    <li>The other player (or players) will guess letters one at a time.</li> 
    <li>If the guessed letter is in the word, the first player writes the letter in all its correct positions. If the guessed letter is not in the word, the first player draws one part of the hangman diagram.</li> 
    <li>The hangman diagram typically consists of the following parts: base, post, crossbeam, rope, head, body, left arm, right arm, left leg, right leg.</li> 
    <li>The game continues with players guessing letters until they either guess the complete word correctly or the hangman diagram is fully drawn (indicating a loss).</li> 
</ol> 
<h2>Rules</h2> 
<ul> 
    <li>Players must guess one letter at a time.</li> 
    <li>If the same incorrect letter is guessed more than once, it does not count as an additional incorrect guess.</li> 
    <li>The game ends when the entire word is guessed correctly or when the hangman diagram is fully drawn.</li> 
</ul> 
<h2>Winning and Losing</h2> 
<p>The player wins if they can guess the entire word before the hangman diagram is completed. The player loses if the hangman diagram is fully drawn before the word is guessed.</p>
<div class="border-top pt-3">
    <small class="text-muted">
        Register to play now! <a class="ml-2" href="{{ url_for('user.register') }}">Play Now</a>
    </small>
</div>
<script> 
    document.addEventListener('DOMContentLoaded', () => { 
        const bgm = document.getElementById('bgm');  
        const bgmMuted = localStorage.getItem('bgmMuted'); 
        if (bgmMuted === 'true') { 
            bgm.muted = true; 
        } 
        else { 
            bgm.muted = false; 
        }
    });
</script>
{% endblock %}

hangman/templates/account.html
{% extends "layout.html" %}
<audio id="bgm" autoplay loop> 
    <source src="{{ url_for('static', filename='audio/bgm.mp3') }}" type="audio/mpeg"> 
    Your browser does not support the audio element. 
</audio>
{% block content %}
    <div class="content-section">
        <div class="media">
            <img class="rounded-circle account image" src="{{ picture }}" width="125" height="125">
            <div class="media-body">
                <h2 class="account-heading">{{ current_user.username }}</h2>
                <p class="text-secondary">{{ current_user.email }}</p>
            </div>
        </div>
            <form method="POST" action="" enctype="multipart/form-data">
                {{ form.hidden_tag() }}
                <fieldset class="form-group">
                    <legend class="border-bottom mb-4">Account</legend>
                    <div class="form-group">
                        {{ form.username.label(class="form-control-label") }}
    
                        {% if form.username.errors %}
                            {{ form.username(class="form-control form-control-lg is-invalid") }}
                            <div class="invalid-feedback">
                                {% for error in form.username.errors %}
                                    <span>{{ error }}</span>
                                {% endfor %}
                            </div>
                        {% else %}
                            {{ form.username(class="form-control form-control-lg") }}
                        {% endif %}
                    </div>
                    <div class="form-group">
                        {{ form.email.label(class="form-control-label") }}
                        {% if form.email.errors %}
                            {{ form.email(class="form-control form-control-lg is-invalid") }}
                            <div class="invalid-feedback">
                                {% for error in form.email.errors %}
                                    <span>{{ error }}</span>
                                {% endfor %}
                            </div>
                        {% else %}
                            {{ form.email(class="form-control form-control-lg") }}
                        {% endif %}
                    </div>
                    <div class="form-group">
                        {{ form.picture.label() }}
                        {{ form.picture(class="form-control-file") }}
                        {% if form.picture.errors %}
                            {% for error in form.picture.errors %}
                            <span class="text-danger">{{ error }}</span></br>
                            {% endfor %}
                        {% endif %}
                    </div>
                </fieldset>
                <div class="form-group">
                    {{ form.submit(class="btn btn-outline-info") }}
                </div>
            </form>
    </div>
<script> 
document.addEventListener('DOMContentLoaded', () => { 
    const bgm = document.getElementById('bgm');  
    const bgmMuted = localStorage.getItem('bgmMuted'); 
    if (bgmMuted === 'true') { 
        bgm.muted = true; 
    } 
    else { 
        bgm.muted = false; 
    }
});
</script>
{% endblock %}

hangman/templates/confirm_email.html
{% extends "layout.html" %}
{% block content %}
    <div class="content-section">
        <h1>Email Verified</h1> 
        <p>Thank you for verifying your email address. Your account is now activated and you can proceed to use our services.</p> 
        <a href="{{ url_for('user.login') }}" class="button">Log In</a>
    </div>
{% endblock content %}

hangman/templates/home.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <style>
        .flash-message{
            position: fixed;
            top: 20px;
            right: 20px;
            z-index: 1000;
        }
    </style>
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='main.css') }}">

    {% if title %}
        <title>Hangman- {{ title }}</title>
    {% else %}
        <title>Hangman</title>
    {% endif %}
</head>
<body>
    <audio id="bgm" autoplay loop> 
        <source src="{{ url_for('static', filename='audio/bgm.mp3') }}" type="audio/mpeg"> 
        Your browser does not support the audio element. 
    </audio>
    <header class="site-header">
        <nav class="navbar navbar-expand-md navbar-dark bg-steel fixed-top">
            <div class="container">
                <a class="navbar-brand mr-4" href="/">Hangman</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggle" aria-controls="navbarToggle" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarToggle">
                    <div class="navbar-nav mr-auto">
                        <a class="nav-item nav-link" href="{{ url_for('user.home') }}">Home</a>
                        <a class="nav-item nav-link" href="{{ url_for('user.rules') }}">Rules</a>
                    </div>
                    <!-- Navbar Right Side -->
                    <div class="navbar-nav ml-auto">
                        <a href="/profile" class="user-account d-flex align-items-center mb-3"> 
                            <img src="{{ url_for('static',filename='profile_pics/'+ current_user.picture) }}" class="rounded-circle" alt="User Avatar" width="75" height="75"> 
                            <span class="ml-2">{{ current_user.username }}</span>
                        </a>
                    </div>
                </div>
            </div>
        </nav>
    </header>
    <main role="main" class="container mt-5 pt-5">
        <div class="row justify-content-center">
            <div class="col-md-8 text-center">
                {% with messages = get_flashed_messages(with_categories=true) %}
                    {% if messages %}
                        {% for category, message in messages %}
                            <div class="alert alert-{{ category }} flash-message">
                                {{ message }}
                            </div>
                        {% endfor %}
                    {% endif %}
                {% endwith %}
                <div class="container d-flex flex-column align-items-center">
                    <!-- Hangman drawing -->
                    <svg class="hangman mb-3" width="200" height="250">
                        <!-- Gallows -->
                        <line class="part" x1="50" y1="200" x2="150" y2="200" stroke="black" stroke-width="5"/>
                        <line class="part" x1="100" y1="50" x2="100" y2="200" stroke="black" stroke-width="5"/>
                        <line class="part" x1="100" y1="50" x2="150" y2="50" stroke="black" stroke-width="5"/>
                        <line class="part" x1="150" y1="50" x2="150" y2="80" stroke="black" stroke-width="5"/>
                        <!-- Hangman -->
                        <circle class="part" cx="150" cy="100" r="20" stroke="black" stroke-width="3" fill="none"/>
                        <line class="part" x1="150" y1="120" x2="150" y2="160" stroke="black" stroke-width="3"/>
                        <line class="part" x1="150" y1="130" x2="130" y2="150" stroke="black" stroke-width="3"/>
                        <line class="part" x1="150" y1="130" x2="170" y2="150" stroke="black" stroke-width="3"/>
                        <line class="part" x1="150" y1="160" x2="130" y2="190" stroke="black" stroke-width="3"/>
                        <line class="part" x1="150" y1="160" x2="170" y2="190" stroke="black" stroke-width="3"/>
                    </svg>
                    <!-- Play button -->
                    <button class="btn btn-success play-button mt-3" onclick="window.location.href='/play'">Play</button>
                </div>
            </div>
        </div>
    </main>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>

    <script>
        function animateHangman() {
            const parts = document.querySelectorAll('.hangman .part');
            let delay = 0;
            parts.forEach(part => {
                setTimeout(() => {
                    part.style.opacity = 1;
                }, delay);
                delay += 500;  // Reduce delay to 500ms between each part
            });
            setTimeout(() => {
                parts.forEach(part => {
                    part.style.opacity = 0;
                });
                animateHangman();
            }, delay);
        }

        animateHangman();
    </script>
    <script>setTimeout(function() { 
    const flashMessages = document.querySelectorAll('.flash-message'); 
    flashMessages.forEach(function(message) { 
    message.style.display = 'none'; 
    }); 
    }, 
    5000); // 5000 milliseconds = 5 seconds 
    </script>
    <script> 
    document.addEventListener('DOMContentLoaded', () => { 
        const bgm = document.getElementById('bgm');  
        const bgmMuted = localStorage.getItem('bgmMuted'); 
        if (bgmMuted === 'true') { 
            bgm.muted = true; 
        } 
        else { 
            bgm.muted = false; 
        }
    });
</script>
</body>
</html>

hangman/templates/layout.html
<!DOCTYPE html>
<html>
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='main.css') }}">

    {% if title %}
        <title>Hangman- {{ title }}</title>
    {% else %}
        <title>Hangman</title>
    {% endif %}
</head>
<body>
    <header class="site-header">
      <nav class="navbar navbar-expand-md navbar-dark bg-steel fixed-top">
        <div class="container">
          <a class="navbar-brand mr-4" href="/">Hangman</a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggle" aria-controls="navbarToggle" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarToggle">
            <div class="navbar-nav mr-auto">
              <a class="nav-item nav-link" href="{{ url_for('user.home') }}">Home</a>
            </div>
            <!-- Navbar Right Side -->
            <div class="navbar-nav">
              <a class="nav-item nav-link" href="{{ url_for('user.update') }}">Update</a>
              <a class="nav-item nav-link" href="{{ url_for('user.login') }}">Login</a>
              <a class="nav-item nav-link" href="{{ url_for('user.register') }}">Register</a>
            </div>
          </div>
        </div>
      </nav>
    </header>
    <main role="main" class="container">
      <div class="row">
        <div class="col-md-8">
          {% with messages = get_flashed_messages(with_categories=true) %}
            {% if messages %}
              {% for category, message in messages %}
                <div class="alert alert-{{ category }}">
                  {{ message }}
                </div>
              {% endfor %}
            {% endif %}
          {% endwith %}
          {% block content %}{% endblock %}
        </div>
      </div>
    </main>
</body>

hangman/templates/login.html
{% extends "layout.html" %}
{% block content %}
    <div class="content-section">
        <form method="POST" action="">
            {{ form.hidden_tag() }}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Log In</legend>
                <div class="form-group">
                    {{ form.email.label(class="form-control-label") }}
                    {% if form.email.errors %}
                        {{ form.email(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.email.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.email(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-group">
                    {{ form.password.label(class="form-control-label") }}
                    {% if form.password.errors %}
                        {{ form.password(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.password.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.password(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-check">
                    {{ form.remember(class="form-check-input") }}
                    {{ form.remember.label(class="form-check-label") }}
                </div>
            </fieldset>
            <div class="form-group">
                {{ form.submit(class="btn btn-outline-info") }}
                <small class="text-muted ml-2">
                    <a href="{{url_for('user.reset_request')}}">Forgot Password?</a>
                </small>
            </div>
        </form>
    </div>
    <div class="border-top pt-3">
        <small class="text-muted">
            Need An Account? <a class="ml-2" href="{{ url_for('user.register') }}">Sign Up Now</a>
        </small>
    </div>
{% endblock content %}

hangman/templates/lose.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='main.css') }}">

    {% if title %}
        <title>Hangman - {{ title }}</title>
    {% else %}
        <title>Hangman</title>
    {% endif %}
</head>
<body>
    <audio id="bgm" autoplay loop> 
        <source src="{{ url_for('static', filename='audio/lost.mp3') }}" type="audio/mpeg"> 
        Your browser does not support the audio element. 
    </audio>
    <header class="site-header">
        <nav class="navbar navbar-expand-md navbar-dark bg-steel fixed-top">
            <div class="container">
                <a class="navbar-brand mr-4" href="/">Hangman</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggle" aria-controls="navbarToggle" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarToggle">
                    <div class="navbar-nav mr-auto">
                        <a class="nav-item nav-link" href="{{ url_for('user.home') }}">Home</a>
                    </div>
                    <!-- Navbar Right Side -->
                    <div class="navbar-nav">
                        <a class="nav-item nav-link" href="{{ url_for('user.update') }}">Update</a>
                        <a class="nav-item nav-link" href="{{ url_for('user.login') }}">Login</a>
                        <a class="nav-item nav-link" href="{{ url_for('user.register') }}">Register</a>
                    </div>
                </div>
            </div>
        </nav>
    </header>
    <main role="main" class="container mt-5 pt-5">
        <div class="row justify-content-center">
            <div class="col-md-6">
                <div class="container bg-white p-4 rounded shadow">
                    <div class="message text-danger">Game Over!</div>
                    <p>
                        The word was 
                        <a href="https://www.google.com/search?q={{ word }} meaning" target="_blank">{{ word }}</a>
                    </p> 
                    <div class="emoji">😞</div>
                    <button class="btn btn-primary play-again-button mt-3" onclick="window.location.href='/play'">Play Again</button>
                </div>
                <div class="mt-3">
                    <button class="btn btn-secondary" onclick="window.location.href='/home'">Home</button>
                </div>
            </div>
        </div>
    </main>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    <script> 
    document.addEventListener('DOMContentLoaded', () => { 
        const bgm = document.getElementById('bgm');  
        const bgmMuted = localStorage.getItem('bgmMuted'); 
        if (bgmMuted === 'true') { 
            bgm.muted = true; 
        } 
        else { 
            bgm.muted = false; 
        }
    });
</script>
</body>
</html>

hangman/templates/reset_request.html
{% extends "layout.html" %}
{% block content %}
    <div class="content-section">
        <form method="POST" action="">
            {{ form.hidden_tag() }}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">{{legend}}</legend>
                <div class="form-group">
                    {{ form.email.label(class="form-control-label") }}
                    {% if form.email.errors %}
                        {{ form.email(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.email.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.email(class="form-control form-control-lg") }}
                    {% endif %}
                </div>    
            </fieldset>
            <div class="form-group">
                {{ form.submit(class="btn btn-outline-info") }}
            </div>
        </form>
    </div>
{% endblock content %}